# 1. 데이터 적재 및 통합

In [26]:
# 라이브러리 가져오기
import pandas as pd
import numpy as np

In [4]:
# 데이터 가져오기
# read_excel() 기본 동작 : 첫 번째 시트의 데이터만 가져오므로...
# NC Dinos.xlsx 파일을 읽어와주세요.
data = pd.read_excel('data/NC Dinos.xlsx', sheet_name=None)
data

{'2013':     Unnamed: 0  선수명  팀명   경기   타석   타수   안타  홈런  득점  타점  볼넷   삼진  도루  BABIP  \
 0            0  모창민  NC  108  436  395  109  12  57  51  37   68  16  0.307
 1            1  이호준  NC  126  508  442  123  20  46  87  60  109   2  0.324
 2            2  김종호  NC  128  546  465  129   0  72  22  57  100  50  0.352
 3            3  나성범  NC  104  458  404   98  14  55  64  33   95  12  0.279
 4            4  조영훈  NC  120  426  380  107   6  38  39  39   56   4  0.316
 5            5  이현곤  NC   91  161  139   38   0  10   9  16   14   2  0.304
 6            6  이상호  NC  102  138  125   31   0  26  13   9   21  24  0.298
 7            7  강진성  NC    3    3    2    1   0   1   0   1    0   0  0.500
 8            8  조평호  NC   26   86   79   21   2  12   7   6   24   1  0.358
 9            9  박민우  NC   32   48   42   11   0  10   6   5    7   9  0.306
 10          10  박정준  NC   77  195  167   41   4  24  21  23   44   4  0.303
 11          11  이승호  NC    2    1    0    0   0   0   0   1    0   1      -
 12          12  마낙길  NC   24   31   29    9   0   5   0   1    5   2  0.375
 13          13  김성욱  NC    4    4    4    1   0   0   1   0    2   0  0.500
 14          14  강구성  NC    2    2    2    0   0   0   0   0    0   0  0.000
 15          15  지석훈  NC  104  356  309   68   3  25  35  30   82   2  0.285
 16          16  김종찬  NC    5    7    7    1   0   0   0   0    3   0  0.250
 17          17  차화준  NC   58  121  106   24   1  18   7  12   29   4  0.295
 18          18  김동건  NC    7   17   16    2   1   1   1   1    7   0  0.125
 19          19  이창섭  NC    5    5    5    0   0   0   0   0    2   0  0.000

        타율    출루율    장타율    OPS   wOBA   WAR
 0   0.276  0.339  0.443  0.782  0.353  2.31
 1   0.278  0.362  0.475  0.837  0.373  1.85
 2   0.277  0.376  0.333  0.709  0.339  1.55
 3   0.243  0.319  0.416  0.735  0.329  1.50
 4   0.282  0.350  0.413  0.763  0.348  0.83
 5   0.273  0.361  0.324  0.685  0.327  0.52
 6   0.248  0.299  0.320  0.619  0.289  0.16
 7   0.500  0.667  1.000  1.667  0.671  0.10
 8   0.266  0.318  0.418  0.736  0.329  0.09
 9   0.262  0.333  0.286  0.619  0.296  0.07
 10  0.246  0.335  0.353  0.688  0.320  0.06
 11      -  1.000      -      -  0.712  0.06
 12  0.310  0.333  0.345  0.678  0.317 -0.03
 13  0.250  0.250  0.250  0.500  0.234 -0.03
 14  0.000  0.000  0.000  0.000  0.000 -0.06
 15  0.220  0.300  0.330  0.630  0.293 -0.09
 16  0.143  0.143  0.143  0.286  0.134 -0.11
 17  0.226  0.306  0.311  0.617  0.289 -0.12
 18  0.125  0.176  0.313  0.489  0.216 -0.14
 19  0.000  0.000  0.000  0.000  0.000 -0.14  ,
 '2014':     Unnamed: 0   선수명  팀명   경기   타석   타수   안타  홈런  득점   타점  볼넷   삼진  도루  BABIP  \
 0            0   테임즈  NC  125  514  443  152  37  95  121  58   99  11  0.367
 1            1   나성범  NC  123  536  477  157  30  88  101  43  128  14  0.397
 2            2   박민우  NC  118  491  416  124   1  87   40  56   89  50  0.373
 3            3   손시헌  NC   97  361  307   90   5  39   39  34   53   2  0.331
 4            4   지석훈  NC  114  238  212   58   6  26   34  16   46   1  0.323
 5            5   이호준  NC  122  500  424  115  23  59   78  67  104   2  0.305
 6            6   권희동  NC  101  252  221   63   7  39   36  25   43   6  0.324
 7            7   모창민  NC  122  468  419  110  16  62   72  37   82  14  0.289
 8            8   이종욱  NC  124  495  438  126   6  73   79  40   60  15  0.313
 9            9   김준완  NC    6    5    4    2   0   1    0   1    1   1  0.667
 10          10   최재원  NC    2    2    1    0   0   1    0   1    1   0      -
 11          11   마낙길  NC    2    2    1    0   0   1    0   1    0   0  0.000
 12          12   조영훈  NC   92  124  111   29   6  15   22  10   26   1  0.288
 13          13   김태우  NC    4    5    5    1   0   0    0   0    3   0  0.500
 14          14  박명환*  NC    2    1    1    0   0   0    0   0    1   0      -
 15          15   조평호  NC    2    2    2    0   0   0    0   0    0   0  0.000
 16          16   강민국  NC    6    3    3    0   0   0    0   0    0   0  0.000
 17          17    허준  NC   28   36   29    5   0   2    1   5   10   0  0.263
 18          18   김성욱  NC   26   26   23    4   1   6    1   3    9   1  0.231
 19          19   노진혁  NC   25   16   16    3   1   3    2   0    7   0  0.250

        타율    출루율    장타율    OPS   wOBA   WAR
 0   0.343  0.422  0.688  1.110  0.456  6.36
 1   0.329  0.400  0.597  0.997  0.424  5.94
 2   0.298  0.392  0.399  0.791  0.365  2.73
 3   0.293  0.368  0.414  0.782  0.349  1.52
 4   0.274  0.340  0.462  0.802  0.352  0.97
 5   0.271  0.371  0.481  0.852  0.369  0.88
 6   0.285  0.363  0.443  0.806  0.353  0.62
 7   0.263  0.320  0.413  0.733  0.319  0.17
 8   0.288  0.343  0.411  0.754  0.332  0.13
 9   0.500  0.600  0.500  1.100  0.509  0.11
 10  0.000  0.500  0.000  0.500  0.363  0.01
 11  0.000  0.500  0.000  0.500  0.363  0.01
 12  0.261  0.325  0.459  0.784  0.337 -0.02
 13  0.200  0.200  0.400  0.600  0.244 -0.03
 14  0.000  0.000  0.000  0.000  0.000 -0.03
 15  0.000  0.000  0.000  0.000  0.000 -0.07
 16  0.000  0.000  0.000  0.000  0.000 -0.10
 17  0.172  0.294  0.276  0.570  0.268 -0.11
 18  0.174  0.269  0.348  0.617  0.272 -0.15
 19  0.188  0.188  0.375  0.563  0.231 -0.18  ,
 '2015':     Unnamed: 0  선수명  팀명   경기   타석   타수   안타  홈런   득점   타점   볼넷   삼진  도루  \
 0            0  테임즈  NC  142  595  472  180  47  130  140  103   91  40
 1            1  나성범  NC  144  622  564  184  28  112  135   33  127  23
 2            2  박민우  NC  141  617  520  158   3  111   47   73  108  46
 3            3  이호준  NC  131  518  449  132  24   48  110   61  102   0
 4            4  김종호  NC  133  486  424  125   4   90   36   44   65  41
 5            5  조영훈  NC  103  146  124   35   8   20   35   19   36   3
 6            6  손시헌  NC  140  508  440  108  13   56   58   36   66   3
 7            7  이종욱  NC  125  504  440  118   5   63   52   54   78  17
 8            8  모창민  NC  103  239  214   62   6   23   35   18   52   5
 9            9  지석훈  NC  137  466  415  111  11   53   46   23   85   4
 10          10  용덕한  NC   50   49   42   12   0    4    5    5    8   2
 11          11  최재원  NC  114  102   85   21   2   31   13   10   29  14
 12          12  박정준  NC   19   24   21    8   0    2    2    0    5   0
 13          13  김태군  NC  144  474  421  107   6   45   52   25   77   1
 14          14  조평호  NC   22   22   22    8   1    4    3    0    6   0
 15          15  이창섭  NC   15    8    5    0   0    0    0    3    3   0
 16          16  김준완  NC   30   54   44   10   0   12    2   10   10   2
 17          17  강구성  NC    4    5    5    1   0    0    0    0    0   0
 18          18  강민국  NC    1    2    2    0   0    0    0    0    1   0
 19          19  김태진  NC    1    3    3    0   0    0    0    0    0   0

     BABIP     타율    출루율    장타율    OPS   wOBA    WAR
 0   0.390  0.381  0.497  0.790  1.287  0.520  11.73
 1   0.374  0.326  0.373  0.553  0.926  0.390   4.46
 2   0.373  0.304  0.399  0.404  0.803  0.364   3.52
 3   0.332  0.294  0.381  0.510  0.891  0.381   2.19
 4   0.338  0.295  0.364  0.394  0.758  0.340   1.03
 5   0.329  0.282  0.372  0.540  0.912  0.389   1.00
 6   0.260  0.245  0.319  0.398  0.717  0.316   0.85
 7   0.315  0.268  0.351  0.368  0.719  0.322   0.84
 8   0.352  0.290  0.340  0.439  0.779  0.340   0.76
 9   0.311  0.267  0.328  0.383  0.711  0.317   0.51
 10  0.353  0.286  0.375  0.310  0.685  0.326   0.44
 11  0.352  0.247  0.366  0.412  0.778  0.350   0.30
 12  0.500  0.381  0.458  0.476  0.934  0.417   0.25
 13  0.293  0.254  0.307  0.354  0.661  0.294   0.25
 14  0.467  0.364  0.364  0.591  0.955  0.401   0.18
 15  0.000  0.000  0.375  0.000  0.375  0.286  -0.01
 16  0.294  0.227  0.370  0.227  0.597  0.308  -0.04
 17  0.200  0.200  0.200  0.400  0.600  0.242  -0.04
 18  0.000  0.000  0.000  0.000  0.000  0.000  -0.06
 19  0.000  0.000  0.000  0.000  0.000  0.000  -0.09  }

In [5]:
# 시트별 데이터를 각각 개별 변수에 저장
nc13, nc14, nc15 = data.values()

In [12]:
nc13.shape

(20, 20)

In [13]:
nc14.shape

(20, 20)

In [14]:
nc15.shape

(20, 20)

In [16]:
nc13.columns

Index(['Unnamed: 0', '선수명', '팀명', '경기', '타석', '타수', '안타', '홈런', '득점', '타점',
       '볼넷', '삼진', '도루', 'BABIP', '타율', '출루율', '장타율', 'OPS', 'wOBA', 'WAR'],
      dtype='object')

In [17]:
nc15.head(2)

,Unnamed: 0,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR
0,0,테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.390,0.381,0.497,0.790,1.287,0.52,11.73
1,1,나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.39,4.46

In [23]:
# nc13, nc14, nc15 데이터의 Unnamed: 0 컬럼을 삭제해주세요.
#nc13.drop('Unnamed: 0', axis=1, inplace=True)
del nc14['Unnamed: 0']
del nc15['Unnamed: 0']

In [25]:
nc15

,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR
0,테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.390,0.381,0.497,0.790,1.287,0.520,11.73
1,나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.390,4.46
2,박민우,NC,141,617,520,158,3,111,47,73,108,46,0.373,0.304,0.399,0.404,0.803,0.364,3.52
3,이호준,NC,131,518,449,132,24,48,110,61,102,0,0.332,0.294,0.381,0.510,0.891,0.381,2.19
4,김종호,NC,133,486,424,125,4,90,36,44,65,41,0.338,0.295,0.364,0.394,0.758,0.340,1.03
5,조영훈,NC,103,146,124,35,8,20,35,19,36,3,0.329,0.282,0.372,0.540,0.912,0.389,1.00
6,손시헌,NC,140,508,440,108,13,56,58,36,66,3,0.260,0.245,0.319,0.398,0.717,0.316,0.85
7,이종욱,NC,125,504,440,118,5,63,52,54,78,17,0.315,0.268,0.351,0.368,0.719,0.322,0.84
8,모창민,NC,103,239,214,62,6,23,35,18,52,5,0.352,0.290,0.340,0.439,0.779,0.340,0.76
9,지석훈,NC,137,466,415,111,11,53,46,23,85,4,0.311,0.267,0.328,0.383,0.711,0.317,0.51
10,용덕한,NC,50,49,42,12,0,4,5,5,8,2,0.353,0.286,0.375,0.310,0.685,0.326,0.44
11,최재원,NC,114,102,85,21,2,31,13,10,29,14,0.352,0.247,0.366,0.412,0.778,0.350,0.30
12,박정준,NC,19,24,21,8,0,2,2,0,5,0,0.500,0.381,0.458,0.476,0.934,0.417,0.25
13,김태군,NC,144,474,421,107,6,45,52,25,77,1,0.293,0.254,0.307,0.354,0.661,0.294,0.25
14,조평호,NC,22,22,22,8,1,4,3,0,6,0,0.467,0.364,0.364,0.591,0.955,0.401,0.18
15,이창섭,NC,15,8,5,0,0,0,0,3,3,0,0.000,0.000,0.375,0.000,0.375,0.286,-0.01
16,김준완,NC,30,54,44,10,0,12,2,10,10,2,0.294,0.227,0.370,0.227,0.597,0.308,-0.04
17,강구성,NC,4,5,5,1,0,0,0,0,0,0,0.200,0.200,0.200,0.400,0.600,0.242,-0.04
18,강민국,NC,1,2,2,0,0,0,0,0,1,0,0.000,0.000,0.000,0.000,0.000,0.000,-0.06
19,김태진,NC,1,3,3,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,-0.09

In [29]:
# nc13, 14, 15 선수 자료중 '선수명' 컬럼을 이용해 선수명에 동명이인이 있는지 여부와
# 선수 명수를 출력해보겠습니다.
# .Unique()는 중복값을 배제하고 내부 데이터를 보여줍니다.
#nc13['선수명']
nc13.선수명.unique()

array(['모창민', '이호준', '김종호', '나성범', '조영훈', '이현곤', '이상호', '강진성', '조평호',
       '박민우', '박정준', '이승호', '마낙길', '김성욱', '강구성', '지석훈', '김종찬', '차화준',
       '김동건', '이창섭'], dtype=object)

In [31]:
print(nc13.선수명.unique())
print(len(nc13.선수명.unique()))

['모창민' '이호준' '김종호' '나성범' '조영훈' '이현곤' '이상호' '강진성' '조평호' '박민우' '박정준' '이승호'
 '마낙길' '김성욱' '강구성' '지석훈' '김종찬' '차화준' '김동건' '이창섭']
20

In [41]:
# 14년도 동명이인 여부
len(nc14.선수명)

20

In [42]:
nc14.선수명.unique()

array(['테임즈', '나성범', '박민우', '손시헌', '지석훈', '이호준', '권희동', '모창민', '이종욱',
       '김준완', '최재원', '마낙길', '조영훈', '김태우', '박명환*', '조평호', '강민국', '허준',
       '김성욱', '노진혁'], dtype=object)

In [38]:
# 15년도 동명이인 여부
nc15.선수명.unique()

array(['테임즈', '나성범', '박민우', '이호준', '김종호', '조영훈', '손시헌', '이종욱', '모창민',
       '지석훈', '용덕한', '최재원', '박정준', '김태군', '조평호', '이창섭', '김준완', '강구성',
       '강민국', '김태진'], dtype=object)

In [45]:
# set(집합자료형) 은 내부에 중복데이터 입력시 1개로 집계합니다.
# set()을 이용하면 다년간 주전이었던 선수 확인 가능
# 13년 ~ 15년까지는 항상 20명의 선수가 데이터로 집계됨
# 14년 ~15년 연속 주전이었던 선수의 인원수
# 14년에도 존재하는 이름이면서 동시에 15년에도 존재하는 이름만 체크
set(nc14.선수명.unique()) & set(nc15.선수명.unique())

{'강민국',
 '김준완',
 '나성범',
 '모창민',
 '박민우',
 '손시헌',
 '이종욱',
 '이호준',
 '조영훈',
 '조평호',
 '지석훈',
 '최재원',
 '테임즈'}

In [46]:
len(set(nc14.선수명.unique()) & set(nc15.선수명.unique()))

13

#### 최종 데이터

2013, 2014, 2015 데이터를 모두 합치되 각각이 몇 년도 데이터인지 알 수 있도록 '연도' 값을 추가

In [ ]:
# nc13, nc14, nc15 변수에 '연도' 컬럼 추가
# nc13에는 2013을, nc14에는 2014를 스칼라 값으로..
# 이와 같이 연도 식별이 가능하게 컬럼을 추가해주세요.

In [48]:
# 13년도

nc13['연도'] = 2013
nc13.head()

,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR,연도
0,모창민,NC,108,436,395,109,12,57,51,37,68,16,0.307,0.276,0.339,0.443,0.782,0.353,2.31,2013
1,이호준,NC,126,508,442,123,20,46,87,60,109,2,0.324,0.278,0.362,0.475,0.837,0.373,1.85,2013
2,김종호,NC,128,546,465,129,0,72,22,57,100,50,0.352,0.277,0.376,0.333,0.709,0.339,1.55,2013
3,나성범,NC,104,458,404,98,14,55,64,33,95,12,0.279,0.243,0.319,0.416,0.735,0.329,1.50,2013
4,조영훈,NC,120,426,380,107,6,38,39,39,56,4,0.316,0.282,0.350,0.413,0.763,0.348,0.83,2013

In [49]:
nc14['연도'] = 2014

In [50]:
nc15['연도'] = 2015

In [ ]:
# 여러개의 df 결합
# 결합 방식 : 컬럼개수 및 속성이 완전히 같으므로 row길이를 늘려준다.
# 최종 결과는 : 20 + 20 + 20 = (60,20)

In [64]:
nc_result1 = pd.concat([nc13,nc14,nc15])

In [150]:
nc_result1

,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR,연도
0,모창민,NC,108,436,395,109,12,57,51,37,68,16,0.307,0.276,0.339,0.443,0.782,0.353,2.31,2013
1,이호준,NC,126,508,442,123,20,46,87,60,109,2,0.324,0.278,0.362,0.475,0.837,0.373,1.85,2013
2,김종호,NC,128,546,465,129,0,72,22,57,100,50,0.352,0.277,0.376,0.333,0.709,0.339,1.55,2013
3,나성범,NC,104,458,404,98,14,55,64,33,95,12,0.279,0.243,0.319,0.416,0.735,0.329,1.50,2013
4,조영훈,NC,120,426,380,107,6,38,39,39,56,4,0.316,0.282,0.350,0.413,0.763,0.348,0.83,2013
5,이현곤,NC,91,161,139,38,0,10,9,16,14,2,0.304,0.273,0.361,0.324,0.685,0.327,0.52,2013
6,이상호,NC,102,138,125,31,0,26,13,9,21,24,0.298,0.248,0.299,0.320,0.619,0.289,0.16,2013
7,강진성,NC,3,3,2,1,0,1,0,1,0,0,0.500,0.500,0.667,1.000,1.667,0.671,0.10,2013
8,조평호,NC,26,86,79,21,2,12,7,6,24,1,0.358,0.266,0.318,0.418,0.736,0.329,0.09,2013
9,박민우,NC,32,48,42,11,0,10,6,5,7,9,0.306,0.262,0.333,0.286,0.619,0.296,0.07,2013
10,박정준,NC,77,195,167,41,4,24,21,23,44,4,0.303,0.246,0.335,0.353,0.688,0.320,0.06,2013
11,이승호,NC,2,1,0,0,0,0,0,1,0,1,-,-,1.000,-,-,0.712,0.06,2013
12,마낙길,NC,24,31,29,9,0,5,0,1,5,2,0.375,0.310,0.333,0.345,0.678,0.317,-0.03,2013
13,김성욱,NC,4,4,4,1,0,0,1,0,2,0,0.500,0.250,0.250,0.250,0.500,0.234,-0.03,2013
14,강구성,NC,2,2,2,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,-0.06,2013
15,지석훈,NC,104,356,309,68,3,25,35,30,82,2,0.285,0.220,0.300,0.330,0.630,0.293,-0.09,2013
16,김종찬,NC,5,7,7,1,0,0,0,0,3,0,0.250,0.143,0.143,0.143,0.286,0.134,-0.11,2013
17,차화준,NC,58,121,106,24,1,18,7,12,29,4,0.295,0.226,0.306,0.311,0.617,0.289,-0.12,2013
18,김동건,NC,7,17,16,2,1,1,1,1,7,0,0.125,0.125,0.176,0.313,0.489,0.216,-0.14,2013
19,이창섭,NC,5,5,5,0,0,0,0,0,2,0,0.000,0.000,0.000,0.000,0.000,0.000,-0.14,2013
0,테임즈,NC,125,514,443,152,37,95,121,58,99,11,0.367,0.343,0.422,0.688,1.11,0.456,6.36,2014
1,나성범,NC,123,536,477,157,30,88,101,43,128,14,0.397,0.329,0.400,0.597,0.997,0.424,5.94,2014
2,박민우,NC,118,491,416,124,1,87,40,56,89,50,0.373,0.298,0.392,0.399,0.791,0.365,2.73,2014
3,손시헌,NC,97,361,307,90,5,39,39,34,53,2,0.331,0.293,0.368,0.414,0.782,0.349,1.52,2014
4,지석훈,NC,114,238,212,58,6,26,34,16,46,1,0.323,0.274,0.340,0.462,0.802,0.352,0.97,2014
5,이호준,NC,122,500,424,115,23,59,78,67,104,2,0.305,0.271,0.371,0.481,0.852,0.369,0.88,2014
6,권희동,NC,101,252,221,63,7,39,36,25,43,6,0.324,0.285,0.363,0.443,0.806,0.353,0.62,2014
7,모창민,NC,122,468,419,110,16,62,72,37,82,14,0.289,0.263,0.320,0.413,0.733,0.319,0.17,2014
8,이종욱,NC,124,495,438,126,6,73,79,40,60,15,0.313,0.288,0.343,0.411,0.754,0.332,0.13,2014
9,김준완,NC,6,5,4,2,0,1,0,1,1,1,0.667,0.5,0.600,0.5,1.1,0.509,0.11,2014
10,최재원,NC,2,2,1,0,0,1,0,1,1,0,-,0.0,0.500,0.0,0.5,0.363,0.01,2014
11,마낙길,NC,2,2,1,0,0,1,0,1,0,0,0.000,0.0,0.500,0.0,0.5,0.363,0.01,2014
12,조영훈,NC,92,124,111,29,6,15,22,10,26,1,0.288,0.261,0.325,0.459,0.784,0.337,-0.02,2014
13,김태우,NC,4,5,5,1,0,0,0,0,3,0,0.500,0.2,0.200,0.4,0.6,0.244,-0.03,2014
14,박명환*,NC,2,1,1,0,0,0,0,0,1,0,-,0.0,0.000,0.0,0.0,0.000,-0.03,2014
15,조평호,NC,2,2,2,0,0,0,0,0,0,0,0.000,0.0,0.000,0.0,0.0,0.000,-0.07,2014
16,강민국,NC,6,3,3,0,0,0,0,0,0,0,0.000,0.0,0.000,0.0,0.0,0.000,-0.10,2014
17,허준,NC,28,36,29,5,0,2,1,5,10,0,0.263,0.172,0.294,0.276,0.57,0.268,-0.11,2014
18,김성욱,NC,26,26,23,4,1,6,1,3,9,1,0.231,0.174,0.269,0.348,0.617,0.272,-0.15,2014
19,노진혁,NC,25,16,16,3,1,3,2,0,7,0,0.250,0.188,0.188,0.375,0.563,0.231,-0.18,2014
0,테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.39,0.381,0.497,0.79,1.287,0.520,11.73,2015
1,나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.390,4.46,2015
2,박민우,NC,141,617,520,158,3,111,47,73,108,46,0.373,0.304,0.399,0.404,0.803,0.364,3.52,2015
3,이호준,NC,131,518,449,132,24,48,110,61,102,0,0.332,0.294,0.381,0.51,0.891,0.381,2.19,2015
4,김종호,NC,133,486,424,125,4,90,36,44,65,41,0.338,0.295,0.364,0.394,0.758,0.340,1.03,2015
5,조영훈,NC,103,146,124,35,8,20,35,19,36,3,0.329,0.282,0.372,0.54,0.912,0.389,1.00,2015
6,손시헌,NC,140,508,440,108,13,56,58,36,66,3,0.26,0.245,0.319,0.398,0.717,0.316,0.85,2015
7,이종욱,NC,125,504,440,118,5,63,52,54,78,17,0.315,0.268,0.351,0.368,0.719,0.322,0.84,2015
8,모창민,NC,103,239,214,62,6,23,35,18,52,5,0.352,0.29,0.340,0.439,0.779,0.340,0.76,2015
9,지석훈,NC,137,466,415,111,11,53,46,23,85,4,0.311,0.267,0.328,0.383,0.711,0.317,0.51,2015
10,용덕한,NC,50,49,42,12,0,4,5,5,8,2,0.353,0.286,0.375,0.31,0.685,0.326,0.44,2015
11,최재원,NC,114,102,85,21,2,31,13,10,29,14,0.352,0.247,0.366,0.412,0.778,0.350,0.30,2015
12,박정준,NC,19,24,21,8,0,2,2,0,5,0,0.5,0.381,0.458,0.476,0.934,0.417,0.25,2015
13,김태군,NC,144,474,421,107,6,45,52,25,77,1,0.293,0.254,0.307,0.354,0.661,0.294,0.25,2015
14,조평호,NC,22,22,22,8,1,4,3,0,6,0,0.467,0.364,0.364,0.591,0.955,0.401,0.18,2015
15,이창섭,NC,15,8,5,0,0,0,0,3,3,0,0.0,0.0,0.375,0.0,0.375,0.286,-0.01,2015
16,김준완,NC,30,54,44,10,0,12,2,10,10,2,0.294,0.227,0.370,0.227,0.597,0.308,-0.04,2015
17,강구성,NC,4,5,5,1,0,0,0,0,0,0,0.2,0.2,0.200,0.4,0.6,0.242,-0.04,2015
18,강민국,NC,1,2,2,0,0,0,0,0,1,0,0.0,0.0,0.000,0.0,0.0,0.000,-0.06,2015
19,김태진,NC,1,3,3,0,0,0,0,0,0,0,0.0,0.0,0.000,0.0,0.0,0.000,-0.09,2015

In [80]:
# 조건색인을 이용해 2013,2014 데이터만 조회해 보세요.
# nc_result1[(nc_result1['연도']==2013) / (nc_result1['연도']==2014)]
nc_result1[nc_result1['연도']!= 2015]

,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR,연도
0,모창민,NC,108,436,395,109,12,57,51,37,68,16,0.307,0.276,0.339,0.443,0.782,0.353,2.31,2013
1,이호준,NC,126,508,442,123,20,46,87,60,109,2,0.324,0.278,0.362,0.475,0.837,0.373,1.85,2013
2,김종호,NC,128,546,465,129,0,72,22,57,100,50,0.352,0.277,0.376,0.333,0.709,0.339,1.55,2013
3,나성범,NC,104,458,404,98,14,55,64,33,95,12,0.279,0.243,0.319,0.416,0.735,0.329,1.50,2013
4,조영훈,NC,120,426,380,107,6,38,39,39,56,4,0.316,0.282,0.350,0.413,0.763,0.348,0.83,2013
5,이현곤,NC,91,161,139,38,0,10,9,16,14,2,0.304,0.273,0.361,0.324,0.685,0.327,0.52,2013
6,이상호,NC,102,138,125,31,0,26,13,9,21,24,0.298,0.248,0.299,0.320,0.619,0.289,0.16,2013
7,강진성,NC,3,3,2,1,0,1,0,1,0,0,0.500,0.500,0.667,1.000,1.667,0.671,0.10,2013
8,조평호,NC,26,86,79,21,2,12,7,6,24,1,0.358,0.266,0.318,0.418,0.736,0.329,0.09,2013
9,박민우,NC,32,48,42,11,0,10,6,5,7,9,0.306,0.262,0.333,0.286,0.619,0.296,0.07,2013
10,박정준,NC,77,195,167,41,4,24,21,23,44,4,0.303,0.246,0.335,0.353,0.688,0.320,0.06,2013
11,이승호,NC,2,1,0,0,0,0,0,1,0,1,-,-,1.000,-,-,0.712,0.06,2013
12,마낙길,NC,24,31,29,9,0,5,0,1,5,2,0.375,0.310,0.333,0.345,0.678,0.317,-0.03,2013
13,김성욱,NC,4,4,4,1,0,0,1,0,2,0,0.500,0.250,0.250,0.250,0.500,0.234,-0.03,2013
14,강구성,NC,2,2,2,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,-0.06,2013
15,지석훈,NC,104,356,309,68,3,25,35,30,82,2,0.285,0.220,0.300,0.330,0.630,0.293,-0.09,2013
16,김종찬,NC,5,7,7,1,0,0,0,0,3,0,0.250,0.143,0.143,0.143,0.286,0.134,-0.11,2013
17,차화준,NC,58,121,106,24,1,18,7,12,29,4,0.295,0.226,0.306,0.311,0.617,0.289,-0.12,2013
18,김동건,NC,7,17,16,2,1,1,1,1,7,0,0.125,0.125,0.176,0.313,0.489,0.216,-0.14,2013
19,이창섭,NC,5,5,5,0,0,0,0,0,2,0,0.000,0.000,0.000,0.000,0.000,0.000,-0.14,2013
0,테임즈,NC,125,514,443,152,37,95,121,58,99,11,0.367,0.343,0.422,0.688,1.11,0.456,6.36,2014
1,나성범,NC,123,536,477,157,30,88,101,43,128,14,0.397,0.329,0.400,0.597,0.997,0.424,5.94,2014
2,박민우,NC,118,491,416,124,1,87,40,56,89,50,0.373,0.298,0.392,0.399,0.791,0.365,2.73,2014
3,손시헌,NC,97,361,307,90,5,39,39,34,53,2,0.331,0.293,0.368,0.414,0.782,0.349,1.52,2014
4,지석훈,NC,114,238,212,58,6,26,34,16,46,1,0.323,0.274,0.340,0.462,0.802,0.352,0.97,2014
5,이호준,NC,122,500,424,115,23,59,78,67,104,2,0.305,0.271,0.371,0.481,0.852,0.369,0.88,2014
6,권희동,NC,101,252,221,63,7,39,36,25,43,6,0.324,0.285,0.363,0.443,0.806,0.353,0.62,2014
7,모창민,NC,122,468,419,110,16,62,72,37,82,14,0.289,0.263,0.320,0.413,0.733,0.319,0.17,2014
8,이종욱,NC,124,495,438,126,6,73,79,40,60,15,0.313,0.288,0.343,0.411,0.754,0.332,0.13,2014
9,김준완,NC,6,5,4,2,0,1,0,1,1,1,0.667,0.5,0.600,0.5,1.1,0.509,0.11,2014
10,최재원,NC,2,2,1,0,0,1,0,1,1,0,-,0.0,0.500,0.0,0.5,0.363,0.01,2014
11,마낙길,NC,2,2,1,0,0,1,0,1,0,0,0.000,0.0,0.500,0.0,0.5,0.363,0.01,2014
12,조영훈,NC,92,124,111,29,6,15,22,10,26,1,0.288,0.261,0.325,0.459,0.784,0.337,-0.02,2014
13,김태우,NC,4,5,5,1,0,0,0,0,3,0,0.500,0.2,0.200,0.4,0.6,0.244,-0.03,2014
14,박명환*,NC,2,1,1,0,0,0,0,0,1,0,-,0.0,0.000,0.0,0.0,0.000,-0.03,2014
15,조평호,NC,2,2,2,0,0,0,0,0,0,0,0.000,0.0,0.000,0.0,0.0,0.000,-0.07,2014
16,강민국,NC,6,3,3,0,0,0,0,0,0,0,0.000,0.0,0.000,0.0,0.0,0.000,-0.10,2014
17,허준,NC,28,36,29,5,0,2,1,5,10,0,0.263,0.172,0.294,0.276,0.57,0.268,-0.11,2014
18,김성욱,NC,26,26,23,4,1,6,1,3,9,1,0.231,0.174,0.269,0.348,0.617,0.272,-0.15,2014
19,노진혁,NC,25,16,16,3,1,3,2,0,7,0,0.250,0.188,0.188,0.375,0.563,0.231,-0.18,2014

## 2. 2015년 타율이 높은 상위 10명
#### 참고) 동일 타율을 기록한 선수에 대해서는 안타 개수가 많은 순서로 정렬

In [82]:
nc2015 = nc_result1[nc_result1['연도']== 2015]
nc2015

,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR,연도
0,테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.39,0.381,0.497,0.79,1.287,0.520,11.73,2015
1,나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.390,4.46,2015
2,박민우,NC,141,617,520,158,3,111,47,73,108,46,0.373,0.304,0.399,0.404,0.803,0.364,3.52,2015
3,이호준,NC,131,518,449,132,24,48,110,61,102,0,0.332,0.294,0.381,0.51,0.891,0.381,2.19,2015
4,김종호,NC,133,486,424,125,4,90,36,44,65,41,0.338,0.295,0.364,0.394,0.758,0.340,1.03,2015
5,조영훈,NC,103,146,124,35,8,20,35,19,36,3,0.329,0.282,0.372,0.54,0.912,0.389,1.00,2015
6,손시헌,NC,140,508,440,108,13,56,58,36,66,3,0.26,0.245,0.319,0.398,0.717,0.316,0.85,2015
7,이종욱,NC,125,504,440,118,5,63,52,54,78,17,0.315,0.268,0.351,0.368,0.719,0.322,0.84,2015
8,모창민,NC,103,239,214,62,6,23,35,18,52,5,0.352,0.29,0.340,0.439,0.779,0.340,0.76,2015
9,지석훈,NC,137,466,415,111,11,53,46,23,85,4,0.311,0.267,0.328,0.383,0.711,0.317,0.51,2015
10,용덕한,NC,50,49,42,12,0,4,5,5,8,2,0.353,0.286,0.375,0.31,0.685,0.326,0.44,2015
11,최재원,NC,114,102,85,21,2,31,13,10,29,14,0.352,0.247,0.366,0.412,0.778,0.350,0.30,2015
12,박정준,NC,19,24,21,8,0,2,2,0,5,0,0.5,0.381,0.458,0.476,0.934,0.417,0.25,2015
13,김태군,NC,144,474,421,107,6,45,52,25,77,1,0.293,0.254,0.307,0.354,0.661,0.294,0.25,2015
14,조평호,NC,22,22,22,8,1,4,3,0,6,0,0.467,0.364,0.364,0.591,0.955,0.401,0.18,2015
15,이창섭,NC,15,8,5,0,0,0,0,3,3,0,0.0,0.0,0.375,0.0,0.375,0.286,-0.01,2015
16,김준완,NC,30,54,44,10,0,12,2,10,10,2,0.294,0.227,0.370,0.227,0.597,0.308,-0.04,2015
17,강구성,NC,4,5,5,1,0,0,0,0,0,0,0.2,0.2,0.200,0.4,0.6,0.242,-0.04,2015
18,강민국,NC,1,2,2,0,0,0,0,0,1,0,0.0,0.0,0.000,0.0,0.0,0.000,-0.06,2015
19,김태진,NC,1,3,3,0,0,0,0,0,0,0,0.0,0.0,0.000,0.0,0.0,0.000,-0.09,2015

In [96]:
nc2015.sort_values(by=['타율','안타'], axis=0, ascending=False).head(10)

,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR,연도
0,테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.39,0.381,0.497,0.79,1.287,0.520,11.73,2015
12,박정준,NC,19,24,21,8,0,2,2,0,5,0,0.5,0.381,0.458,0.476,0.934,0.417,0.25,2015
14,조평호,NC,22,22,22,8,1,4,3,0,6,0,0.467,0.364,0.364,0.591,0.955,0.401,0.18,2015
1,나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.390,4.46,2015
2,박민우,NC,141,617,520,158,3,111,47,73,108,46,0.373,0.304,0.399,0.404,0.803,0.364,3.52,2015
4,김종호,NC,133,486,424,125,4,90,36,44,65,41,0.338,0.295,0.364,0.394,0.758,0.340,1.03,2015
3,이호준,NC,131,518,449,132,24,48,110,61,102,0,0.332,0.294,0.381,0.51,0.891,0.381,2.19,2015
8,모창민,NC,103,239,214,62,6,23,35,18,52,5,0.352,0.29,0.340,0.439,0.779,0.340,0.76,2015
10,용덕한,NC,50,49,42,12,0,4,5,5,8,2,0.353,0.286,0.375,0.31,0.685,0.326,0.44,2015
5,조영훈,NC,103,146,124,35,8,20,35,19,36,3,0.329,0.282,0.372,0.54,0.912,0.389,1.00,2015

In [98]:
# 특정 컬럼에 .tolist()를 사용하면 파이썬 리스트로 뽑을수도 있습니다.
nc2015.선수명.tolist()

['테임즈',
 '나성범',
 '박민우',
 '이호준',
 '김종호',
 '조영훈',
 '손시헌',
 '이종욱',
 '모창민',
 '지석훈',
 '용덕한',
 '최재원',
 '박정준',
 '김태군',
 '조평호',
 '이창섭',
 '김준완',
 '강구성',
 '강민국',
 '김태진']

## 3. 2013~2015년 선수별 3년 평균 안타 수

- 평균 안타수가 높은 순서로 정렬해서 보이기

In [113]:
hit_result = nc_result1.groupby('선수명')[['안타']].mean().sort_values(by='안타',ascending=False)
hit_result

              안타
선수명
테임즈   166.000000
나성범   146.333333
김종호   127.000000
이호준   123.333333
이종욱   122.000000
김태군   107.000000
손시헌    99.000000
박민우    97.666667
모창민    93.666667
지석훈    79.000000
권희동    63.000000
조영훈    57.000000
이현곤    38.000000
이상호    31.000000
박정준    24.500000
차화준    24.000000
용덕한    12.000000
최재원    10.500000
조평호     9.666667
김준완     6.000000
허준      5.000000
마낙길     4.500000
노진혁     3.000000
김성욱     2.500000
김동건     2.000000
김태우     1.000000
김종찬     1.000000
강진성     1.000000
강구성     0.500000
강민국     0.000000
이승호     0.000000
박명환*    0.000000
이창섭     0.000000
김태진     0.000000

In [115]:
hit_result.head(10)

             안타
선수명
테임즈  166.000000
나성범  146.333333
김종호  127.000000
이호준  123.333333
이종욱  122.000000
김태군  107.000000
손시헌   99.000000
박민우   97.666667
모창민   93.666667
지석훈   79.000000

In [117]:
hit_player = hit_result.head(10).index.tolist()

## 4. 평균 안타수 기준 상위 10위 타자들의 3년간 안타, 홈런, 타율 조회
#### 참고) NaN 값이 있을 경우 '-'로 대체해서 표현

In [152]:
nc_result1.groupby('선수명')[['안타']].mean().sort_values(by='안타',ascending=False)

              안타
선수명
테임즈   166.000000
나성범   146.333333
김종호   127.000000
이호준   123.333333
이종욱   122.000000
김태군   107.000000
손시헌    99.000000
박민우    97.666667
모창민    93.666667
지석훈    79.000000
권희동    63.000000
조영훈    57.000000
이현곤    38.000000
이상호    31.000000
박정준    24.500000
차화준    24.000000
용덕한    12.000000
최재원    10.500000
조평호     9.666667
김준완     6.000000
허준      5.000000
마낙길     4.500000
노진혁     3.000000
김성욱     2.500000
김동건     2.000000
김태우     1.000000
김종찬     1.000000
강진성     1.000000
강구성     0.500000
강민국     0.000000
이승호     0.000000
박명환*    0.000000
이창섭     0.000000
김태진     0.000000

In [154]:
# 조건색인시 .isin(리스트) 을 사용하면, 해당 리스트에 포함된 사람만 조회 가능합니다.
# fancy 인덱싱(조건색인에서 미리 준비된 리스트에 해당하는 목록만 남김)
nc_result1[nc_result1['선수명'].isin(hit_player)]

,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR,연도
0,모창민,NC,108,436,395,109,12,57,51,37,68,16,0.307,0.276,0.339,0.443,0.782,0.353,2.31,2013
1,이호준,NC,126,508,442,123,20,46,87,60,109,2,0.324,0.278,0.362,0.475,0.837,0.373,1.85,2013
2,김종호,NC,128,546,465,129,0,72,22,57,100,50,0.352,0.277,0.376,0.333,0.709,0.339,1.55,2013
3,나성범,NC,104,458,404,98,14,55,64,33,95,12,0.279,0.243,0.319,0.416,0.735,0.329,1.50,2013
9,박민우,NC,32,48,42,11,0,10,6,5,7,9,0.306,0.262,0.333,0.286,0.619,0.296,0.07,2013
15,지석훈,NC,104,356,309,68,3,25,35,30,82,2,0.285,0.220,0.300,0.330,0.630,0.293,-0.09,2013
0,테임즈,NC,125,514,443,152,37,95,121,58,99,11,0.367,0.343,0.422,0.688,1.11,0.456,6.36,2014
1,나성범,NC,123,536,477,157,30,88,101,43,128,14,0.397,0.329,0.400,0.597,0.997,0.424,5.94,2014
2,박민우,NC,118,491,416,124,1,87,40,56,89,50,0.373,0.298,0.392,0.399,0.791,0.365,2.73,2014
3,손시헌,NC,97,361,307,90,5,39,39,34,53,2,0.331,0.293,0.368,0.414,0.782,0.349,1.52,2014
4,지석훈,NC,114,238,212,58,6,26,34,16,46,1,0.323,0.274,0.340,0.462,0.802,0.352,0.97,2014
5,이호준,NC,122,500,424,115,23,59,78,67,104,2,0.305,0.271,0.371,0.481,0.852,0.369,0.88,2014
7,모창민,NC,122,468,419,110,16,62,72,37,82,14,0.289,0.263,0.320,0.413,0.733,0.319,0.17,2014
8,이종욱,NC,124,495,438,126,6,73,79,40,60,15,0.313,0.288,0.343,0.411,0.754,0.332,0.13,2014
0,테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.39,0.381,0.497,0.79,1.287,0.520,11.73,2015
1,나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.390,4.46,2015
2,박민우,NC,141,617,520,158,3,111,47,73,108,46,0.373,0.304,0.399,0.404,0.803,0.364,3.52,2015
3,이호준,NC,131,518,449,132,24,48,110,61,102,0,0.332,0.294,0.381,0.51,0.891,0.381,2.19,2015
4,김종호,NC,133,486,424,125,4,90,36,44,65,41,0.338,0.295,0.364,0.394,0.758,0.340,1.03,2015
6,손시헌,NC,140,508,440,108,13,56,58,36,66,3,0.26,0.245,0.319,0.398,0.717,0.316,0.85,2015
7,이종욱,NC,125,504,440,118,5,63,52,54,78,17,0.315,0.268,0.351,0.368,0.719,0.322,0.84,2015
8,모창민,NC,103,239,214,62,6,23,35,18,52,5,0.352,0.29,0.340,0.439,0.779,0.340,0.76,2015
9,지석훈,NC,137,466,415,111,11,53,46,23,85,4,0.311,0.267,0.328,0.383,0.711,0.317,0.51,2015
13,김태군,NC,144,474,421,107,6,45,52,25,77,1,0.293,0.254,0.307,0.354,0.661,0.294,0.25,2015

In [155]:
top10_player = nc_result1[nc_result1['선수명'].isin(hit_player)]
top10_player

,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR,연도
0,모창민,NC,108,436,395,109,12,57,51,37,68,16,0.307,0.276,0.339,0.443,0.782,0.353,2.31,2013
1,이호준,NC,126,508,442,123,20,46,87,60,109,2,0.324,0.278,0.362,0.475,0.837,0.373,1.85,2013
2,김종호,NC,128,546,465,129,0,72,22,57,100,50,0.352,0.277,0.376,0.333,0.709,0.339,1.55,2013
3,나성범,NC,104,458,404,98,14,55,64,33,95,12,0.279,0.243,0.319,0.416,0.735,0.329,1.50,2013
9,박민우,NC,32,48,42,11,0,10,6,5,7,9,0.306,0.262,0.333,0.286,0.619,0.296,0.07,2013
15,지석훈,NC,104,356,309,68,3,25,35,30,82,2,0.285,0.220,0.300,0.330,0.630,0.293,-0.09,2013
0,테임즈,NC,125,514,443,152,37,95,121,58,99,11,0.367,0.343,0.422,0.688,1.11,0.456,6.36,2014
1,나성범,NC,123,536,477,157,30,88,101,43,128,14,0.397,0.329,0.400,0.597,0.997,0.424,5.94,2014
2,박민우,NC,118,491,416,124,1,87,40,56,89,50,0.373,0.298,0.392,0.399,0.791,0.365,2.73,2014
3,손시헌,NC,97,361,307,90,5,39,39,34,53,2,0.331,0.293,0.368,0.414,0.782,0.349,1.52,2014
4,지석훈,NC,114,238,212,58,6,26,34,16,46,1,0.323,0.274,0.340,0.462,0.802,0.352,0.97,2014
5,이호준,NC,122,500,424,115,23,59,78,67,104,2,0.305,0.271,0.371,0.481,0.852,0.369,0.88,2014
7,모창민,NC,122,468,419,110,16,62,72,37,82,14,0.289,0.263,0.320,0.413,0.733,0.319,0.17,2014
8,이종욱,NC,124,495,438,126,6,73,79,40,60,15,0.313,0.288,0.343,0.411,0.754,0.332,0.13,2014
0,테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.39,0.381,0.497,0.79,1.287,0.520,11.73,2015
1,나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.390,4.46,2015
2,박민우,NC,141,617,520,158,3,111,47,73,108,46,0.373,0.304,0.399,0.404,0.803,0.364,3.52,2015
3,이호준,NC,131,518,449,132,24,48,110,61,102,0,0.332,0.294,0.381,0.51,0.891,0.381,2.19,2015
4,김종호,NC,133,486,424,125,4,90,36,44,65,41,0.338,0.295,0.364,0.394,0.758,0.340,1.03,2015
6,손시헌,NC,140,508,440,108,13,56,58,36,66,3,0.26,0.245,0.319,0.398,0.717,0.316,0.85,2015
7,이종욱,NC,125,504,440,118,5,63,52,54,78,17,0.315,0.268,0.351,0.368,0.719,0.322,0.84,2015
8,모창민,NC,103,239,214,62,6,23,35,18,52,5,0.352,0.29,0.340,0.439,0.779,0.340,0.76,2015
9,지석훈,NC,137,466,415,111,11,53,46,23,85,4,0.311,0.267,0.328,0.383,0.711,0.317,0.51,2015
13,김태군,NC,144,474,421,107,6,45,52,25,77,1,0.293,0.254,0.307,0.354,0.661,0.294,0.25,2015

In [156]:
# 연도, 선수명, 안타, 홈런, 타율 컬럼만 남겨주세요.
top10_player = top10_player[['연도','선수명','안타','홈런','타율']]

In [157]:
top10_player

      연도  선수명   안타  홈런     타율
0   2013  모창민  109  12  0.276
1   2013  이호준  123  20  0.278
2   2013  김종호  129   0  0.277
3   2013  나성범   98  14  0.243
9   2013  박민우   11   0  0.262
15  2013  지석훈   68   3  0.220
0   2014  테임즈  152  37  0.343
1   2014  나성범  157  30  0.329
2   2014  박민우  124   1  0.298
3   2014  손시헌   90   5  0.293
4   2014  지석훈   58   6  0.274
5   2014  이호준  115  23  0.271
7   2014  모창민  110  16  0.263
8   2014  이종욱  126   6  0.288
0   2015  테임즈  180  47  0.381
1   2015  나성범  184  28  0.326
2   2015  박민우  158   3  0.304
3   2015  이호준  132  24  0.294
4   2015  김종호  125   4  0.295
6   2015  손시헌  108  13  0.245
7   2015  이종욱  118   5  0.268
8   2015  모창민   62   6   0.29
9   2015  지석훈  111  11  0.267
13  2015  김태군  107   6  0.254

In [158]:
# 연도, 선수명을 로우로 내리기
# df.set_index(['내릴 컬럼들...'])
top10_player = top10_player.set_index(['연도','선수명'])
top10_player

           안타  홈런     타율
연도   선수명
2013 모창민  109  12  0.276
     이호준  123  20  0.278
     김종호  129   0  0.277
     나성범   98  14  0.243
     박민우   11   0  0.262
     지석훈   68   3  0.220
2014 테임즈  152  37  0.343
     나성범  157  30  0.329
     박민우  124   1  0.298
     손시헌   90   5  0.293
     지석훈   58   6  0.274
     이호준  115  23  0.271
     모창민  110  16  0.263
     이종욱  126   6  0.288
2015 테임즈  180  47  0.381
     나성범  184  28  0.326
     박민우  158   3  0.304
     이호준  132  24  0.294
     김종호  125   4  0.295
     손시헌  108  13  0.245
     이종욱  118   5  0.268
     모창민   62   6   0.29
     지석훈  111  11  0.267
     김태군  107   6  0.254

In [159]:
# 위 자료에 대해 unstack()으로 "연도" 를 컬럼으로 올리겠습니다.
# NaN를 다른 델이터로 교체하기 : .fillna("채울자료")
top10_player.unstack(0).fillna("-")

        안타                  홈런                 타율
연도    2013   2014   2015  2013  2014  2015   2013   2014   2015
선수명
김종호  129.0      -  125.0   0.0     -   4.0  0.277      -  0.295
김태군      -      -  107.0     -     -   6.0      -      -  0.254
나성범   98.0  157.0  184.0  14.0  30.0  28.0  0.243  0.329  0.326
모창민  109.0  110.0   62.0  12.0  16.0   6.0  0.276  0.263  0.290
박민우   11.0  124.0  158.0   0.0   1.0   3.0  0.262  0.298  0.304
손시헌      -   90.0  108.0     -   5.0  13.0      -  0.293  0.245
이종욱      -  126.0  118.0     -   6.0   5.0      -  0.288  0.268
이호준  123.0  115.0  132.0  20.0  23.0  24.0  0.278  0.271  0.294
지석훈   68.0   58.0  111.0   3.0   6.0  11.0  0.220  0.274  0.267
테임즈      -  152.0  180.0     -  37.0  47.0      -  0.343  0.381

In [162]:
# 6.연도별 팀의 총 안타수, 총 홈런수, 총 도루수
# 구해서 보여주세요.
team_result=nc_result1.groupby('연도')[['안타','홈런','도루']].sum()

In [163]:
# 엑셀이나 csv로 빼는 방법
# 엑셀 : .to_excel('경로 및 파일명')
# csv : .to_csv('경로 및 파일명')
team_result.to_excel("NC result.xlsx")